import "./globals.css";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="layout">
          <div className="flex items-center justify-between h-50">
            <div className="flex items-center">
              <div className="flex-shrink-0"></div>
              <div className="hidden md:block">
                <span className="ml-10 flex items-baseline space-x-4 text-white text-3xl">
                  <Image src={'/beer-me-logo.png'} width={150} height={150} alt="beer me logo"/>
                </span>
              </div>
            </div>
          </div>
        </nav>
        {children}
        <div className="bg-gray-800 text-white fixed bottom-0 left-0 right-0 h-28">
          <div className="container mx-auto py-4 px-4 sm:px-6 lg:px-8">
            <span> @ Minutentag - Diego Unanue - 2023 </span>
          </div>
        </div>
      </body>
    </html>
  );
}
